부산대 FE_이세형_1주차 과제 Step1
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #2
Opened 2024-06-25 20:02 UTC by cla6shade

안녕하세요 멘토님,

현업과 각종 행사로 인해 바쁘신 중에도 강의를 위해 힘써주셔서 감사드립니다.

과제를 하면서 어려웠던 점과 궁금한 점을 아래에 정리해봤습니다.

### 과제를 진행하면서 어려웠던 점, 질문

1. eslint와 prettier의 설정이 계속 충돌하면서 어려웠습니다. 여러 문서에서 prettier의 설정과 겹치는 eslint 설정을 eslint-config-prettier을 이용하여 끄라는 권장사항을 많이 봤는데, eslint에서 적용할 수 있는 code convention의 범위가 prettier로 설정할 수 있는 범위보다 훨씬 넓기 때문에 별로 좋은 생각이 아닌 것처럼 보였습니다. 이걸 고민하느라 시간이 좀 오래 걸렸습니다.

2. 패키지 메인테이닝이 제대로 되지 않아 발생하는 불필요한 eslint 에러가 몇몇개 발생했는데, react-in-jsx-scope, import/extensions의 .tsx 모듈 관련 에러였습니다. 에러를 해결하기 위해 해당 옵션들에 대한 린팅 규칙을 비활성화했는데, 이렇게 해도 되는걸까요?

감사합니다.

2024-06-28 10:36 UTC, cla6shade commented
목요일 강의 이후 시간이 조금 부족해서 (알바 일정) 모든 것을 빨리 구현하려니 조금 힘들었습니다. 크게 어려운점은 없었지만 적용해보고싶은게 많아서(전역 스타일링 등) 그중에 우선순위를 골라 적는것도 일이었습니다.

2024-06-29 06:03 UTC, MiaJLee requested changes
세형님 첫번째 과제 빠르게 제출해주셨네요. 고생 많으셨습니다. 👏👏👏👏

PR에 남겨주신 질문 답변 드려볼게요.

> 패키지 메인테이닝이 제대로 되지 않아 발생하는 불필요한 eslint 에러가 몇몇개 발생했는데, react-in-jsx-scope, import/extensions의 .tsx 모듈 관련 에러였습니다. 에러를 해결하기 위해 해당 옵션들에 대한 린팅 규칙을 비활성화했는데, 이렇게 해도 되는걸까요?

`react-in-jsx-scope`
해당 규칙은 React가 JSX 스코프 내에 항상 import되어야 함을 요구하는데요. 
그러나 최근의 React 버전(17 이상)에서는 새로운 [JSX Transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)이 도입되어, 더 이상 JSX에서 React를 import할 필요가 없기에 해당 규칙을 꺼도 문제가 되지 않습니다.

`import/extensions`
해당 규칙은 파일 확장자를 import문에서 어떻게 처리할지 정의하게 되는데요. 해당 규칙을 비활성화 하는 경우 파일 확장자가 무엇인지 명확하게 파악이 어렵고, 코드를 읽는 사람에게 덜 정보를 제공하게 됩니다. 만일 다른 확장자를 가진 파일을 import 하려면 확장자를 명시해야만 하죠.

많은 프로젝트에서는 확장자 없이 파일을 import하기에 해당 규칙을 비활성화 하는 것 역시 큰 문제가 되지는 않을 것 같습니다. 다만 이후 다른 사람들과 함께 관리하는 레포지토리를 수정하는 경우가 생긴다면, 모든 팀원과 해당 변경사항에 대해 공유하고 의견을 나누는 과정이 필요하겠지요-!

2024-06-29 06:38 UTC, MiaJLee commented on src/components/molecules/goodsItem/GoodsItem.tsx
> +        <div css={css`
css 값이 너무 길어지는 경우 컴포넌트의 전체적인 마크업 구조를 파악하기 어려울 수 있습니다.
return 문 하위에서는 컴포넌트의 구조를 쉽게 파악할 수 있도록
emotion styled를 활용하여 밖에서 스타일을 지정하는건 어떨까요?

```ts

const Wrapper = styled.div`
    background-color: #ff8d8d;
    color: #ffffff;
    position: absolute;
    top: 2px;
    left: 2px;
    width: 20px;
    height: 20px;
    z-index: 1;
    border-radius: 5px;
    text-align: center;
`
```

2024-06-29 11:47 UTC, cla6shade commented
멘토님 안녕하세요~

오늘 낮에 코드리뷰 잘 확인했고, 주말 낮부터 하나하나 정성스럽게 써주신 코멘트에 감동받았습니다.. 🥹

리팩토링 중 궁금한 점이 생겨 질문드립니다.

프로젝트 작성 도중에 패키지 매니저(yarn)의 버전이 너무 옛날 버전임을 깨닫고 storybook을 설치할 때가 되어서야 업그레이드 하게 되었습니다. 그 과정에서 yarn berry라는 기능을 알게 되었는데요, ghost dependency를 줄이고 node_modules라는 폴더가 지나치게 무거워지는 현상도 줄일 수 있다는 것을 다른 문서를 통해 알게 되었습니다. (출처: https://toss.tech/article/node-modules-and-yarn-berry)

하지만 저는 현재 yarn berry를 활성화지 않더라도 딱히 불편함을 느낀 적이 없었는데, 앞으로 발생할 가능성이 있는 의존성 문제를 해결하기 위해 도입하는 것이 맞을까요? 아직 개발 경험이 적어서 제가 판단하기는 어려운 내용이었습니다🥹. 그리고 최신 기술들을 도입할 때 주로 어떤 기준을 두고 도입하시는지도 궁금합니다!

바쁘신 중에도 리뷰해주셔서 정말 감사드립니다!

2024-06-29 11:48 UTC, cla6shade commented on src/components/molecules/goodsItem/GoodsItem.tsx
> +        <div css={css`
GoodsItems.styles.tsx 라는 별도의 모듈로 분리해봤습니다!
```tsx
import styled from '@emotion/styled';
import { backgroundColors, textColors } from '@styles/colors';

export const GoodsItemWrapper = styled.div`
  display: flex;
  flex-direction: column;
  width: 120px;
  gap: 6px;
  position: relative;
`;

export const RankingBadge = styled.div`
  background-color: ${backgroundColors.badge};
  color: ${textColors.inset};
  position: absolute;
  top: 2px;
  left: 2px;
  width: 20px;
  height: 20px;
  z-index: 1;
  border-radius: 5px;
  text-align: center;

  p {
    position: absolute;
    margin: auto;
    top: 1px;
    bottom: 0;
    left: 0;
    right: 0;
  }
`;

export const Subtitle = styled.p`
  color: ${textColors.subtitle};
  font-size: 14px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
`;

export const Title = styled.p`
  color: ${textColors.title};
  font-size: 14px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
`;

export const Amount = styled.p`
  color: ${textColors.default};
  font-size: 20px;
  font-weight: bold;
  word-wrap: break-word;
`;
```

2024-06-29 11:48 UTC, cla6shade commented on src/components/atoms/button/Button.tsx
> +          background-color: ${buttonHover[theme]};
감사합니다!

2024-06-29 11:50 UTC, cla6shade commented on src/components/atoms/button/Button.tsx
> +        : (size as FixedSize).height};
원래 type 추정이 가능하기는 한데, IDE에서 size 타입을 파악하지 못해서 명시적으로 적어줬던 것으로 기억합니다. 멘토님께서 추천해주신 메소드를 통해 FixedSize로 변환하여 사용하도록 했습니다!

2024-06-29 11:51 UTC, cla6shade commented on src/components/atoms/button/Button.tsx
> +  }
다른 컴포넌트에서 재사용될 이유가 없다고 생각해서 Button 컴포넌트 내부에 해당 메소드를 위치시켜봤습니다.
```tsx
function getButtonSize(size: ElementSize): FixedSize {
  if (typeof size === 'object') {
    return size;
  }

  return {
    width: 'auto',
    height: size === 'big' ? '60px' : '40px',
  };
}

function Button({
  theme, elementSize, text, ...rest
}: ButtonProps) {
  const size = getButtonSize(elementSize);
// ...
```

2024-06-29 11:54 UTC, cla6shade commented on src/components/atoms/button/Button.tsx
> +    kakao: 'rgb(254, 229, 0)',
```typescript
//...
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: '*', next: ['if', 'for', 'while', 'switch', 'export', 'class', 'function'] },
      { blankLine: 'always', prev: '*', next: 'return' },
      { blankLine: 'always', prev: ['if', 'for', 'while', 'switch', 'export', 'class', 'function'], next: '*' },

      { blankLine: 'always', prev: 'import', next: '*' },
      { blankLine: 'never', prev: 'import', next: 'import' },
    ]
//...
```

조금 변형해서 if, for, while 등의 statement를 사용할 때 전후로 하나의 줄바꿈을 포함되도록 했고, import의 경우 import 이후에 다른 import문이 위치하지 않는 이상 하나의 줄바꿈을 포함하도록 했습니다.

2024-06-29 12:54 UTC, MiaJLee requested changes
세형님~ 코드리뷰 빠르게 반영해주셨네요! 고생하셨습니다 🤩
빠르게 작업 잘 해주셔서 _이렇게 짜볼 수도 있어요~_ 하는 마음으로 추가 리뷰 남겨드렸어요. 확인해보시고 내 취향 아니다 하시면 재끼셔도 괜찮습니다 ㅋㅎ

> yarn berry를 활성화지 않더라도 딱히 불편함을 느낀 적이 없었는데, 앞으로 발생할 가능성이 있는 의존성 문제를 해결하기 위해 도입하는 것이 맞을까요? 아직 개발 경험이 적어서 제가 판단하기는 어려운 내용이었습니다🥹. 그리고 최신 기술들을 도입할 때 주로 어떤 기준을 두고 도입하시는지도 궁금합니다!

실무에서도 종종 CICD 시간 단축 또는 개발 효율성을 높이기 위해 최신 기술을 리서치하기도 하는데요. 일반적인 엔터프라이즈급의 회사에서는 기존에 사용하고 있는 (오래된) 라이브러리가 많고, 또 수정하기 어려운 레거시 코드도 있기 마련입니다. 때문에 새로운 기술을 내 맘대로 도입하는 것은 쉽지 않은 일이라 생각이 되어요. 장점이 뛰어난 최신 기술들이라도 기존의 코드에 적용했을때 문제가 없을지, 충분히 테스트 하는 과정이 가장 중요하게 여겨지는 것 같아요. 또 오래된 기술에 비해 최신기술은 갑자기 업데이트가 중단되어버릴지도 모르다보니 더 조심스럽구요!

찾아보신 것과 같이 yarn berry는 기존의 의존성 문제를 해결할 수 있는 좋은 대안으로 등장했습니다! 제가 속한 팀에서도 빌드 배포 효율성 향상을 위해 yarn berry 도입을 고려했던 적이 있는데요, 여러 이슈로 인해 해당 기술 도입을 하지 못했던 기억이 납니다 😅 하지만 팀원 모두가 yarn berry의 장점과 단점에 대해 배우게 되었죠!

저는 당장 불편함이 없으시다면 급하게 도입하실 필요는 없다고 생각이 되어요. (오히려 이런 저런 라이브러리도 추가되고, 앱이 좀 커지고 나서 문제상황이 생겼을때 얀베리를 적용하기 전후 데이터를 비교해보는 것도 재미있을 것 같기도 하구요.)

새로운 기술에 대해 관심을 갖고 지속적으로 찾아보려는 마인드!! 개발자로서 너무너무 멋진 태도라고 생각합니다. 시간이 되신다면 한번 검토해보시고 적용해보고 동료들에게 공유해보는 것도 좋겠네요 :)

2024-06-29 12:54 UTC, MiaJLee commented on src/components/molecules/goodsItem/GoodsItems.styles.tsx
> +`;
스타일 컴포넌트에서도 중복되는 부분은 분리하여 확장하는 방법도 있답니다 :) 

```suggestion
export const Title = styled.p`
  color: ${textColors.title};
  font-size: 14px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
`;

export const Subtitle = styled(Title)`
  color: ${textColors.subtitle};
`;

```

2024-06-29 14:54 UTC, cla6shade commented on src/components/atoms/input/Input.styles.tsx
> +import { InputProps } from '@components/atoms/input/Input';
제가 몰랐던 부분이네요! 컴파일 이후 순환 참조 에러가 발생할 수 있다는 점을 이번에 처음 알았습니다 ㅎㅎ..
자주 쓰이는 타입들을 정의하는 types/index.d.ts로 분리해봤습니다!
```typescript
import { InputHTMLAttributes } from 'react';
import ElementSize from '@styles/size';

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  elementSize: ElementSize,
  invalid?: boolean,
  errorMessage?: string,
}
```

2024-06-29 14:57 UTC, cla6shade commented on src/components/molecules/goodsItem/GoodsItems.styles.tsx
> +`;
멘토님 가이드에 따라 아래와 같이 수정해봤습니다! 
```tsx
export const Title = styled.p`
  color: ${textColors.title};
  font-size: 14px;
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
`;

export const Subtitle = styled(Title)`
  color: ${textColors.subtitle};
`;
```

2024-06-29 15:41 UTC, cla6shade commented
주말인데도 리뷰해주셔서 정말 감사드립니다..! 제가 쉬시는데 방해가 된건 아닌지 걱정이 될 정도에요..🥲
코드리뷰부터 질문 답변까지 큰 도움이 되었습니다!

특히 새로운 기술을 도입할 때 어떤 기준을 통해 도입하는지 말씀해주셔서 정말 큰 도움이 됐습니다. yarn berry를 검색해보면 대부분이 pnp 방식의 좋은점을 설명하고 이슈에 대해서는 다루지 않더라구요.. 앞으로 테스트를 거쳐서 직접 적용해봐야겠다는 생각이 들었습니다.

남은 주말동안 잘 쉬시고 다음주에 또 과제 PR로 찾아뵙겠습니다.
감사합니다!!

2024-06-30 01:12 UTC, MiaJLee approved these changes
LGTM🍀 고생 많으셨습니다-!

2024-06-30 03:17 UTC, merged