부산대 FE_최윤성_1주차 과제 Step1
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #44
Opened 2024-06-28 07:36 UTC by yunseong0404

2024-06-29 09:25 UTC, MiaJLee requested changes
윤성님 안녕하세요 :)
첫번째 과제 제출 고생하셨습니다~  👍 

README.md 파일이 누락된 것 같아요.
README에 폴더 구조에 대한 설명과 퀴즈에 대한 답변을 달아 추가 커밋 해주세요

아직 Step 2, 3 과제가 업데이트 되지 않은 것 같은데, 확인 부탁드려요!

2024-06-29 09:25 UTC, MiaJLee commented on src/Components/Buttons/PinkBtn.js
PinkBtn 컴포넌트를 생성하는 것도 좋지만 재사용성을 고려했을때,
버튼 컴포넌트의 가장 기본이 되는 Btn.js 또는 Button.js 컴포넌트를 생성하여
색상을 props로 넘겨주는 방식도 고려해보시면 좋을 것 같습니다!
PinkBtn은 현재 다양한 옵션를 주어 사용하기는 어려운 컴포넌트로 생각되어요-!

2024-06-29 09:25 UTC, MiaJLee commented on package.json
<img width="476" alt="스크린샷 2024-06-29 오후 4 32 47" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-react-foundation/assets/48678660/9e6eaa4a-912b-4bba-baa6-bf0393fbb18c">

앱 다운로드 후 실행 시 위와 같은 warning 메세지가 확인되는데요-!

앱의 의존성 중 하나인 babel-preset-react-app이 의존성을 선언하지 않은 채로
@babel/plugin-proposal-private-property-in-object 패키지를 가져오고 있어서 발생하는 오류라고 합니다.

해당 에러 수정을 위해 
"@babel/plugin-proposal-private-property-in-object"을 devDependencies에 추가해야합니다.

터미널에서 다음의 명령을 실행하여 devDependency에 추가하면 해결이 됩니다.

```shell
npm install --save-dev @babel/plugin-proposal-private-property-in-object
```

2024-06-29 09:25 UTC, MiaJLee commented on .eslintrc.json
> +    ],
윤성님~ 해당 경로를 무시하도록 처리하신 이유가 무엇일까요?

@/로 시작하는 절대경로를 사용하는 임포트를 모두 무시하도록 처리하고 있는데요. 절대 경로를 사용하여 모듈을 쉽게 임포트 하려는 의도지만, @/로 시작하는 모든 경로가 무시되기 때문에, 실제로 존재하지 않는 파일이나 모듈을 임포트하는 코드가 있더라도 이를 에러로 찾아낼 수 없게 됩니다. 이후 개발 과정에서 실수를 찾는데 오랜 시간이 소요될 수 있을 것 같아요.

잠재적인 문제가 있으니 필요한 경우에 특정 디렉토리나 파일에 대해서만 해당 규칙을 적용하는 것은 어떨까요?

2024-06-29 09:25 UTC, MiaJLee commented on tsconfig.paths.json
> +}
다음과 같이 수정하여도 동일하게 동작하는 것을 확인하실 수 있습니다 :)

```suggestion
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "@/*": ["*"],
      "@Assets/*": ["Assets/*"],
      "@Pages/*": ["Pages/*"],
      "@Components/*": ["Components/*"],
      "@Styles/*": ["Styles/*"]
    }
  }
}

```

2024-06-29 09:25 UTC, MiaJLee commented on package-lock.json
사용하고 계신 패키지 매니저에 따라 yarn.lock 이나 package-lock.json 파일 둘 중 하나만 남기셔도 무방할 것 같습니다-!

2024-07-01 09:25 UTC, MiaJLee requested changes
윤성님~ 아직 처리되지 않은 이슈들이 남아있어 다시 수정 요청 드립니다.
확인하시고 모두 수정되면 코멘트 부탁드릴게요~

2024-07-01 09:25 UTC, MiaJLee commented on .storybook/main.ts
> +  staticDirs: ['..\\public'],
staticDirs 경로가 잘못되어 storybook 실행이 안되네요~
수정 되어야 합니다

2024-07-01 09:25 UTC, MiaJLee commented on README.md
>  # react-gift-react-foundation
과제 요구사항에 리드미에 디렉토리 구조 추가가 필요한 것으로 알고 있습니다.
추가해주세요~

2024-07-01 09:25 UTC, MiaJLee commented on src/Components/Buttons/PinkBtn.js
> +      <Btn>Button</Btn>
PinkBtn 안에 Btn이 있는 구조는 좀 어색한 것 같아요~
가장 base가 될 수 있는 컴포넌트를 생성하고, 이를 활용하여 분홍색 버튼을 생성하는게 더 여러 버튼을 만들 수 있는 방법이겠죠?
Pinkbtn 컴포넌트 대신 Btn 컴포넌트를 만들어 봅시다.
Btn 컴포넌트를 만들고, 색상을 props로 넘기는 방식으로 수정해볼까요?

2024-07-01 09:25 UTC, MiaJLee commented on src/stories/Button.stories.ts
> +import type { Meta, StoryObj } from '@storybook/react';
stories 하위의 불필요한 파일은 제거해도 될 것 같아요.

2024-07-01 09:25 UTC, MiaJLee commented on tsconfig.paths.json
> +      "@Styles/*": ["./Styles/*"]
paths는 수정이 되지 않았네요~

2024-07-03 08:20 UTC, yunseong0404 commented
피드백 주신 부분 모두 수정했습니다!

2024-07-03 09:18 UTC, MiaJLee commented
고생하셨습니다~! 👍🏻👍🏻

2024-07-03 09:18 UTC, merged