강원대 FE_이예지_1주차_과제
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #48
Opened 2024-06-28 10:50 UTC by yeahzee0421

멘토님 안녕하세요! 과제 진행 방법에 혼동이 생겨 step1과 step2,3를 다른 브랜치에서 진행하여 추가로 PR 올리게 되었습니다.

이번 과제를 진행하면서 필요한 style들 정의할 때 **css 파일로 분리하는 방법**과 **`React.CSSProperties`를 사용하는 방법** 두가지로 구현을 해보았습니다. 멘토님께서는 어떤 방법을 더 추천하시고 적절하다고 생각하시는지, 다른 좋은 방법이 있다면 무엇인지 피드백 주시면 감사하겠습니다:)

그리고 모든 컴포넌트에 _'해당 Element의 기본 속성들을 모두 사용할 수 있게 해요'_ 라는 요구사항이 있었는데, 어떻게 하면 해당 element의 기본 속성을 모두 사용할 수 있도록 구현할 수 있는지 궁금합니다. 

마지막으로 제가 사정상 잠깐 해외에 나와있어 마지막 요구사항인 Grid, Container 컴포넌트를 시간 내에 구현하지 못했습니다. 귀국하자마자 주신 피드백 꼼꼼히 읽고 학습하여 구현하도록 하겠습니다.

2024-06-29 09:39 UTC, yujo11 requested changes
안녕하세요 예지님~~ 만나서 반갑습니다 첫번쨰 리뷰네요 ㅎㅎ

이번 과제에서는 구현된 코드 자체가 많지 않아 한번쯤 생각해보면 좋은 것들에 대해서 질문 위주로 리뷰를 많이 남겼습니다 ㅎㅎ 

>이번 과제를 진행하면서 필요한 style들 정의할 때 css 파일로 분리하는 방법과 React.CSSProperties를 사용하는 방법 두가지로 구현을 해보았습니다. 멘토님께서는 어떤 방법을 더 추천하시고 적절하다고 생각하시는지, 다른 좋은 방법이 있다면 무엇인지 피드백 주시면 감사하겠습니다:)

상황에 따라 달리지고 정답이 존재하는 부분은 아닌데요. 그렇기 떄문에 

1. 두 가지 방법에는 각각 어떤 장단점이 있는지 살펴보고
2. 두 가지 방법 또는 CSS Modules, Styled Components 등 다른 방법을 사용해서 코드베이스에서 스타일을 적용하는 방식이 일관되도록 리팩터링 해보시면 좋을거 같습니다

React에서 스타일을 적용하는 방법을 크게 두 분류로 나눈다면 CSS와 CSS in JS로 나눠볼 수 있을거 같은데요. CSS로 작성하는 것과 CSS in JS로 작성하는 것에는 어떤 차이가 있고 어떤 장단점이 있는지 찾아보시면 좋을거 같습니다 ㅎㅎ

프론트엔드에서 스타일을 적용하기 위해 많이 사용되는 라이브러리들은 키워드만 남겨두고 갈테니 나중에 시간 되시면 각 라이브러리들을 한번 살펴보며 어떤 철학을 가지고 어떤 문제를 해결하기 위해 세상에 나왔는지 살펴보시면 좋겠네요 ㅎㅎ

- Styled Components
- Emotion
- TailwindCSS
- CSS Modules
- vanilla-extract

---

>eslint 설치 관련

`--force` , `--legacy-peer-deps` 옵션을 사용하게 되면 추후 호환성 문제가 생길 수 있기 때문에 사용하지 않는 것을 권장드리고 싶습니다.

초반 프로젝트 설정 과정에서 많은 부침을 겪을 수 있지만 막상 한번 하고나면 그 다음부터는 프로젝트 세팅을 어렵지 않게 할 수 있는데요. 그렇기 떄문에 한번 처음부터 다시 차근차근 프로젝트를 세팅해보시는 것도 추천드리고 싶네요

>폴더 구조

연관있는 컴포넌트끼리 Folder를 통해 가깝게 위치시키는 방법을 사용하셨는데 좋은 방법이라고 생각합니다 ㅎㅎ 지금은 아직 프로젝트 규모가 작아 폴더구조 관련해서 크게 피드백 드릴 내용이 없는데 추후 다시 요청주시면 확인해보도록 하겠습니다!


---

첫 번째 미션 진행하느라 고생 많으셨습니다 예지님~~ 코멘트와 리뷰 확인하시고 다시 리뷰요청 부탁드려요 ~~

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/Button/Button.tsx
>그리고 모든 컴포넌트에 '해당 Element의 기본 속성들을 모두 사용할 수 있게 해요' 라는 요구사항이 있었는데, 어떻게 하면 해당 element의 기본 속성을 모두 사용할 수 있도록 구현할 수 있는지 궁금합니다.

이 질문에 대한 답변인데요 지금은 ButtonProps를 예지님이 정의한 속성만 받을 수 있도록 사용하고 있는데 `extends`를 통해 기본 HTML 엘리먼트의 Interface를 확장하는 방법을 찾아보시면 좋을거 같습니다 ㅎㅎ

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/Button/Button.tsx
> +  size?: 'small' | 'large' | 'responsive';
여기는 optional로 되어 있는데 사용하는 곳에서 아무런 값도 넘기지 않으면 Button은 어떤 모양이 되나요? Optional로 prop을 받을 때 default value도 같이 설정되어 있으면 좋을거 같습니다 ㅎㅎ

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/Form/UnderlineTextField/UnderlineTextField.tsx
> +const TextField: React.FC<FieldProps> = ({ disabled, invalid, size }) => (
`Input`이라는 이름 대신 `TextFiled`라는 이름을 사용하신 이유가 있나요? 파일 이름은 `UnderlineTextField`인데 컴포넌트 이름은 `TextField`인 이유도 궁금하네요

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/Form/UnderlineTextField/UnderlineTextFiled.stories.tsx
> +  tags: ['autodocs'],
👍 👍 👍

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/Image/Image.tsx
> +  return <img src={src} style={heightStyle} alt="imageSample" />;
`<img>` 태그의 `alt`는 어떤 역할을 해줄까요? 항상 같은 값이 들어가도 괜찮을까요?

2024-06-29 09:39 UTC, yujo11 commented on kakao-gift/src/components/common/GoodsItem/RankingItem/RankingItem.tsx
> +    color: '#fff',
이런 폰트 사이즈나 색상 등은 한 곳에 모아서 변수로 관리하며 사용하면 애플리케이션 전체에서 일관된 스타일을 적용하는데 도움이 될거 같네요 ㅎㅎ

2024-07-01 03:24 UTC, yeahzee0421 commented on README.md
https://github.com/yeahzee0421/react-gift-react-foundation/commit/4cd774f409b38a2747c9482e5993a93c790ad87e

리드미에 실행 가이드 추가했습니다 !

2024-07-01 03:36 UTC, yeahzee0421 commented on kakao-gift/package.json
> +  "dependencies": {
dependencies에는 애플리케이션 동작과 직접적으로 연관된 라이브러리를 설치합니다.

```
npm install 라이브러리명
```

devDependencies에는 프로그램 동작과 직접적인 연관은 없지만, 개발할 때 필요한 라이브러리를 설치합니다. devDependencies에 설치된 라이브러리는 배포할 때 포함되지 않습니다. eslint와 prettier는 devDependencies로 설치하는게 좋을 것 같습니다.
```
npm install 라이브러리명 --save-dev,  npm install 라이브러리명 -D
```

2024-07-01 12:37 UTC, yeahzee0421 reviewed
리뷰 확인 후 수정사항 반영했습니다.!

2024-07-03 13:47 UTC, yujo11 commented
코멘트 꼼꼼하게 확인하고 답변 남겨주셔서 감사합니다 예지님 ㅎㅎ 고생 많으셨어요~~!

2024-07-03 13:47 UTC, merged