부산대 FE_차기은_1주차 과제 Step3
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #52
Opened 2024-06-28 12:07 UTC by harugi7

2024-06-29 11:35 UTC, MiaJLee requested changes
기은님 반가워요. 첫번째 과제 고생 많으셨습니다-! 😀
몇가지 수정하면 좋을 포인트들을 정리하여 리뷰하였습니다.
앞서 올려주신 step1, step2 내용도 현 pr에 포함되어 있어 한번에 리뷰하도록 할게요.

현재 `react-gift-react-foundation` 디렉토리 하위에 파일들이 위치하고 있는데요.
해당 파일들을 디렉토리 밖 root에 위치하도록 수정부탁드립니다.

CRA와 storybook에서 자동생성된 파일들, 에셋들이 있는데요 해당 파일들도 정리해주시면 좋을 것 같아요 :)

과제 요구사항인 README.md 파일에 폴더 구조에 대한 설명 추가도 부탁드리겠습니다.

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/public/index.html
cra에서 자동 생성된 파일들 중에서도 불필요한 것은 없을까 한번 확인해보는게 어떨까요?
index.html 에도 여러 태그가 생성되어있는데, 지워도 괜찮은 것이 있을지, 또는 과제에 맞게 수정되면 좋을 내용은 없을지 한번 고민해보세요!

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/src/Components/Button/Button.tsx
> +            : 'yellow'};
삼항연산자를 사용하여 background-color를 설정하고 계시네요!
삼항연산자는 참 편리한 문법이지만, 위와 같이 중첩하여 사용하는 경우 가독성이 떨어지는 문제가 있습니다.
따라서 중첩된 삼항연산자 패턴은 지양하는 것이 좋아요.
위 경우는 if문이나 switch문을 사용하여 수정해보면 가독성이 크게 개선될 것 같아요-!

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/src/Components/Image/Image.stories.ts
> +    src: 'https://via.placeholder.com/400x300',
'https://via.placeholder.com/400x300' 값이 반복적으로 사용되고 있는데,
해당 문자열은 따로 상수로 빼서 사용하면 반복을 줄일 수 있을 것 같아요 :)

```js
const IMAGE_URL = 'https://via.placeholder.com/400x300';

…
args: {
    src: IMAGE_URL
}

```

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/src/Components/Image/Image.tsx
> +        : 'auto'};
이곳에 사용된 nested 삼항연산자도 개선해볼까요?

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/tsconfig.json
> +    }
현재 디렉토리에 맞게 사용이 가능한 절대 경로를 추가해보는 것은 어떨까요?

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/src/Components/Button/Button.tsx
> +const ButtonStyled = styled.button<ButtonProps>`
반복적으로 `props`을 사용하여 스타일을 계산하는 부분은 동작 자체에는 문제가 없으나,
컴포넌트의 로직과 스타일링이 한데 모여 있어 코드를 처음 보는 사람이 이해하는데는 시간이 소요될 수 있다는 점이 아쉽습니다.

스타일을 객체로 분리하면, 컴포넌트의 로직과 스타일이 분리되어, 코드의 가독성이 향상될 수 있어요.
아래와 같이 스타일 관련 코드를 분리한다면 특정 테마의 스타일을 더 쉽게 이해하고 수정할 수 있을 것 같습니다.
또 컴포넌트가 렌더링 될 때마다 불필요한 계산을 줄일 수 있습니다. 
(현재는 큰 차이가 없겠지만, 대규모 어플리케이션이 된다면 이 또한 성능과 연관이 될 수 있겠지요.)

```tsx
// 테마별 스타일 객체 예시
const themeStyles = {
  outline: {
    backgroundColor: 'transparent',
    outline: '1px solid lightGray',
    color: 'black',
  },
  black: {
    backgroundColor: 'black',
    color: 'white',
  },
  // 추가 테마 스타일...
};

// ButtonStyled 내에서 themeStyles 사용 예시
background-color: ${props => themeStyles[props.theme].backgroundColor};
```

2024-06-29 11:35 UTC, MiaJLee commented on react-gift-react-foundation/README.md
> +# Getting Started with Create React App
README에는 처음 보는 사람도 쉽게 이해 가능하도록 레포지토리에 대한 설명을 추가하는 것이 좋습니다.
CRA에서 추가된 내용은 정리하고, 기은님이 작업하신 과제의 디렉토리 구조나 앱에 대한 설명을 추가해보는 것이 어떨까요?

2024-07-02 05:14 UTC, harugi7 commented
안녕하세요 멘토님! 친절하고 자세하게 리뷰해주셔서 정말 감사합니다! 
피드백 해주신 것들을 최대한 반영해보려하였습니다!.
확인해보시고 comment 달아주시면 감사하겠습니다^0^
항상 고생해주셔서 감사합니다.

2024-07-02 09:31 UTC, MiaJLee approved these changes
고생하셨습니다~~
반영되지 않은 피드백들은 다음 PR에 반영해봅시다!

2024-07-02 09:32 UTC, merged