강원대 FE_최서린_1주차 과제
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #64
Opened 2024-06-28 14:14 UTC by seorinnn

안녕하세요! 저는 강원대학교 FE 최서린이라고 합니다.
시간 내주셔서 감사합니다!

현재 프로젝트를 실행하면 에러가 나는 상황인데,
원래 커밋은 프로젝트가 정상적으로 동작하는 상황에만 해야 한다는 것을 알면서도
일단 질문을 하여 피드백을 받은 후에 문제를 해결해야 할 것 같아서 일단 커밋했습니다 ..
 

제가 1단계 과제를 마무리한 후 2단계 과제를 수행하기 전,
3단계 과제(README.md 에 질문 3개 답변 작성하기)를 수행하였습니다.

그래서 1,3단계를 마무리하고 2단계를 진행하기 위해 storybook을 설치 후 구글링을 통해 버튼 컴포넌트를 구현하기 위한 코드를 작성 후, `npm run storybook` 명령어를 통해 스토리북 서버를 켰습니다. 

그런데 (아래 코드는 에러메시지 일부입니다)
```
Failed to compile.
src/components/Button/Button.stories.tsx
[eslint] 
  Line 1:19:   Strings must use singlequote                      quotes
  Line 2:16:   'StoryFn' is defined but never used               no-unused-vars
  Line 2:31:   Strings must use singlequote                      quotes
```
와 같은 에러가 뜨면서 스토리북의 서버가 꺼지는 문제가 발생하였습니다. 작은따옴표를 사용해야 하는데 제 코드에서 큰따옴표를 사용했기 때문에 생긴 문제라고 판단한 저는 vscode 설정에서 전부 작은따옴표를 사용하도록 변경한 후 vscode에서 모든 큰따옴표를 작은따옴표로 수정하였습니다. 

하지만 그럼에도 불구하고 

```
Line 2:10:   'StoryFn' is defined but never used                            no-unused-vars
  Line 2:31:   Unable to resolve path to module '@storybook/react/types-6-0'  import/no-unresolved
  Line 3:18:   'ButtonProps' is defined but never used                        no-unused-vars
  Line 3:37:   Missing file extension "tsx" for "./Button"                    import/extensions
  Line 25:40:  Function component is not a function declaration               react/function-component-definition
  Line 25:50:  JSX not allowed in files with extension '.tsx'                 react/jsx-filename-extension
  Line 25:58:  Prop spreading is forbidden                                    react/jsx-props-no-spreading

src/components/Button/Button.tsx
  Line 6:13:   'ButtonProps' is not defined  
```

와 같은 에러가 뜨고, 이 과정에서 해결법을 찾아보면서 .eslintrc.js 파일과 .prettier.js 파일 내용을 계속 수정하기를 반복했습니다. 하지만 그 두 파일을 수정하고나서는 스토리북 서버 말고도 그냥 `npm run start` 명령어를 통해 켠 프로젝트 서버에서도 에러가 났습니다.

```
[eslint] 
src/App.tsx
  Line 4:10:  JSX not allowed in files with extension '.tsx'  react/jsx-filename-extension

src/index.tsx
  Line 4:19:   Missing file extension "ts" for "./styles/reset"  import/extensions
  Line 5:17:   Missing file extension "tsx" for "./App"          import/extensions
  Line 11:5:   JSX not allowed in files with extension '.tsx'    react/jsx-filename-extension
  Line 14:24:  Missing trailing comma                            comma-dangle

Search for the keywords to learn more about each error.
```

아무리 생각해봐도 eslint 설정에 관한 문제인 것 같은데, 1단계만 수행하였을 때는 나지 않던 에러가 2단계를 수행하는 과정에서 갑자기 나는 이유를 알 수가 없습니다 ㅠㅠ

이전에는 eslint 설정이 적용되지 않고 있었는데 제가 2단계를 수행하는 과정에서 eslint 가 적용되면서 에러가 나게 된 것인지 ....

에러 메시지를 보면 확장자의 문제가 있는 것 같은데, 
제 .eslintrc.js 파일과 tsconfig.json 파일의 코드를 읽어보았을 때 어디가 문제인지 잘 모르겠습니다 ..

과제를 완벽히 수행하지 못하게 되어 너무 아쉽고 속상한 마음이 듭니다 ㅠㅠ
멘토님이 피드백 해주시기 전까지 찾아보면서 해결하기 위해 노력해보고 있겠습니다 ..

피드백 부탁드립니다! 감사합니다

2024-06-28 14:59 UTC, lazy-sky requested changes
안녕하세요 서린님, 이번 리뷰를 맡게 된 김하늘이라고 합니다. 잘 부탁드립니다.

다소 아쉬운 마음이 드시겠지만 그래도 먼저 CRA를 이용하여 프로젝트를 시작하게 되셨네요. 리액트로의 첫걸음을 축하드립니다.

일단 코드를 둘러보는 것에 앞서 당장 문제 상황부터 해결해봐야 할 것 같네요. 동작하지 않는 코드 단계라면 일단 돌아가게 만들어야 하고, 무엇이 더 좋은 코드인가를 따지는 것은 그 다음 문제니까요.

대부분의 에러는 에러 로그만 잘 살펴봐도 해결할 수 있습니다. 일단 `npm run start`로 실행시킨 개발 서버 실행 문제를 해결해봅시다.

첫 번째 줄에 이 에러는 eslint 문제이고 `App.tsx` 4번째 라인에서 발생했으며, 그 원인은 `.tsx` 파일에서는 JSX가 허용되지 않기 때문이라고 나와있네요. 그리고 그 근거는 eslint의 `react/jsx-filename-extension` 룰 때문이라고 말해주고 있습니다. (참고로 이 규칙은 `eslint-plugin-react`에 포함되어 있습니다.)
 
구글에 해당 룰에 대해 검색해보니 아래 문서를 찾을 수 있었습니다.
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md
Rule Options를 보시면 현재 겪는 문제를 해결할 수 있는 방법들이 보이네요!

```js
"rules": {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
}
```

우리는 타입스크립트 파일을 쓰고 있으니 약간의 응용이 필요하겠죠?

일단은 첫 리뷰이니 만큼 바로 정답 자체를 알려주기보단 제가 어떤식으로 문제를 파악하고 해결에 도달할 수 있게 되었는지를 중심으로 이야기드려보았습니다. 혹시 충분히 노력했음에도 도저히 겪는 문제들을 해결해내지 못하신다면 다시 알려주세요! 처음은 누구에게나 어렵습니다. 기다리고 있겠습니다!

2024-06-29 06:48 UTC, seorinnn commented
멘토님이 말씀해주신 에러 해결 과정을 학습하여
일단 `npm run start` 를 입력했을 때 개발 서버에서 난 에러들을 해결했습니다!

멘토님의 피드백을 통해 에러를 해결할 수 있는 방법에 대해 조금 더 알게되었고,
결국 해결하게 되어서 정말 기쁩니다 ㅎㅎ

혹시 가능하시다면 1단계와 3단계 과제에 대한 피드백을 해 주실 수 있으신가요?!

아래는 학습 내용을 기억하기 위해 제가 해결한 과정을 적은 내용입니다!

## 에러 해결 과정

### 1. eslint react/jsx-filename-extension 관련 에러

```
[eslint]
src/App.tsx
  Line 4:10:  JSX not allowed in files with extension '.tsx'  react/jsx-filename-extension
```

- `npm run start`를 입력했을 때 서버에서 이러한 에러가 떴다. 멘토님께서 주신 피드백으로 에러를 해결하기 위해 노력했다.
- 에러 메시지를 통해 이 에러는 eslint 문제라는 것을 알 수 있었다. 또한 `App.tsx` 4번째 라인에서 발생한 에러이며, .tsx 파일에서 JSX가 허용되지 않기 때문에 발생한 에러라는 것을 알 수 있었다. 또한 그 근거는 eslint의 `react/jsx-filename-extension` 룰 때문이라는 것이다.
- 멘토님의 말씀대로 `react/jsx-filename-extension` 에 대해 검색해보았고, 관련 자료를 찾을 수 있었다.

[[eslint-plugin-react/docs/rules/jsx-filename-extension.md at master · jsx-eslint/eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md)](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md)

- 이 규칙 옵션 중 기본적으로 .jsx를 허용하는 extensions 속성이 있었다. .eslintrc.js 파일에서 아래와 같은 코드를 추가하니 위 에러가 해결되었다.

```tsx
"rules": {
"react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
}
```

### 2. Missing file extension "ts" 에러

```
src/index.tsx
  Line 4:19:   Missing file extension "ts" for "./styles/reset"  import/extensions
  Line 5:17:   Missing file extension "tsx" for "./App"          import/extensions
```

- 위와 같이 `index.tsx` 파일에서 `reset.ts`, `App.tsx` 파일을 import 해 올 때 확장자가 없음에 대한 에러가 발생하였다.
- 1번째 에러를 해결할 때 에러의 근거를 확인했던 것처럼, 이번에는 eslint의 `import/extensions` 룰 때문이라는 것을 알 수 있었다.
- 구글링해보니 eslint 설정 파일에서 `import/extensions` 룰을 조정해 파일 확장자를 생략할 수 있게 할 수 있었다.

```
rules: {
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
  },
```

- 위와 같이 설정해주니 에러가 해결되었다.

### 3. Missing trailing comma  comma-dangle 에러

```tsx
[eslint] 
src/index.tsx
  Line 14:24:  Missing trailing comma  comma-dangle
```

- 위 에러는 객체를 선언할 때 가장 마지막 요소에 comma 가 없을 때 발생하는 오류이다.
- 내 생각에는 마지막에 comma가 있으면 그 이후에 다른 요소들이 나와야 할 것 같다는 생각이 드므로 이 설정을 없애기로 했다.
- .eslintrc.js 파일에 `"comma-dangle": ["error", "never"]` 코드를 추가하니 에러가 해결되었다.

---

아직 `npm run storybook` 을 입력하면 스토리북 서버에서 에러가 나는 상황이라 ..
2단계(storybook) 과 관련된 에러는 열심히 해결해보도록 하겠습니다!
(해결이 되면 또 바로 코멘트를 달기 위해 달려오도록 하겠습니다)

(storybook 서버 에러 메시지 일부)

```
src/components/Button/Button.stories.tsx
[eslint] 
  Line 2:10:   'StoryFn' is defined but never used                            no-unused-vars
  Line 2:31:   Unable to resolve path to module '@storybook/react/types-6-0'  import/no-unresolved
  Line 3:18:   'ButtonProps' is defined but never used                        no-unused-vars
  Line 12:42:  Unexpected trailing comma                                      comma-dangle
  Line 13:8:   Unexpected trailing comma                                      comma-dangle
  Line 18:60:  Unexpected trailing comma                                      comma-dangle
  Line 19:8:   Unexpected trailing comma                                      comma-dangle
  Line 21:35:  Unexpected trailing comma                                      comma-dangle
  Line 22:4:   Unexpected trailing comma                                      comma-dangle
```

2024-06-30 05:51 UTC, lazy-sky requested changes

2024-06-30 05:51 UTC, lazy-sky commented on .eslintrc.js
> +    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
겪었던 문제를 정확히 해결하기 위해서 `'.ts'` 와 `'.tsx'`도 추가해주셔아 합니다.

2024-06-30 05:51 UTC, lazy-sky commented on README.md
> +- 함수형 컴포넌트에서는 `useState Hook` 을 사용하여 상태를 업데이트하고 React에서 감지한다.
다소 부족한 설명입니다. 
함수 컴포넌트에서 상태를 업데이트하는 데는`useState` 외에도 여러 가지 방법이 있습니다. 근본적으로 리액트가 상태 변화를 감지하는 과정에 대해서 이해하려면 '리액트는 state를 immutable한다.'는 사실을 이해해야 하는데, 여유가 되실 때 이 개념에 대해 학습하시는 것을 추천드립니다.

2024-07-01 10:09 UTC, seorinnn commented
안녕하세요 멘토님!
Button 컴포넌트를 구현하고 Input 컴포넌트를 구현하는 과정에서 질문이 생겼습니다.

Button 컴포넌트와 같은 형식으로 Input 컴포넌트를 생성하였는데,
`npm run storybook` 을 입력하면 에러가 뜹니다.

```
ERROR in src/components/Input/Input.stories.tsx:28:3
TS2322: Type 'string' is not assignable to type 'undefined'.
    26 | export const Small = Template.bind({});
    27 | Small.args = {
  > 28 |   size: 'small',
       |   ^^^^
    29 |   placeholder: 'Small Input',
    30 | };
    31 |

ERROR in src/components/Input/Input.stories.tsx:34:3
TS2322: Type 'string' is not assignable to type 'undefined'.
    32 | export const Large = Template.bind({});
    33 | Large.args = {
  > 34 |   size: 'large',
       |   ^^^^
    35 |   placeholder: 'Large Input',
    36 | };
    37 |

ERROR in src/components/Input/Input.stories.tsx:40:3
TS2322: Type 'string' is not assignable to type 'undefined'.
    38 | export const Responsive = Template.bind({});
    39 | Responsive.args = {
  > 40 |   size: 'responsive',
       |   ^^^^
    41 |   placeholder: 'Responsive Input',
    42 | };
    43 |
```

위와 같은 에러가 떴습니다. 
TypeScript에서 `size` 속성에 대해 정의된 타입과 스토리에서 할당된 값 간의 불일치 때문에 발생하는 것 같은데, 구글링을 하여 여러 해결법들을 시도해보아도 해결하지 못했습니다.
(그런데 막상 스토리북 서버에서는 제가 구현한 Button과 Input 컴포넌트가 잘 뜹니다..)

코드를 확인하다가 알아낸 점은
`Button.tsx` 에서
```
const Button: React.FC<ButtonProps> = ({
  theme = 'outline',
  size = 'large',
  children,
  ...props
}) 
```
이 부분의 `size` 에 마우스 커서를 올려보면 `(parameter) size: 'large' | 'small' | 'responsive'` 라고 뜹니다.

그런데 `Input.tsx` 에서 
```
const Input: React.FC<InputProps> = ({
  size = 'large',
  disabled = false,
  invalid = false,
  ...props
})
```
이 부분의 `size`에 마우스 커서를 올리면 `(parameter) size: string` 라고 뜹니다.
여기서도 타입과 관련해 차이가 있는 것 같은데, 코드의 형식을 일관되게 작성하였다고 생각했는데 왜 에러가 나는 것인지 궁금합니다 ㅠㅠ

답변 부탁드립니다! 읽어주셔서 감사합니다 ㅎㅎ

2024-07-02 09:13 UTC, lazy-sky commented
분명 버튼을 만들 때와 똑같이 작성했다고 생각했는데 타입 에러가 나는 걸까요? 분명 InputProps와 ButtonProps는 상당히 유사하게 쓰여진 것처럼 보입니다. 차이점은 intersection(&) 뒷부분입니다. html의 input 태그에는 원래 size 속성이 있습니다. 그러니 Input 컴포넌트의 size 속성의 이름을 바꾸면 해결될 거예요.

그럼 여기서 문제, 왜 하필이면 size가 undefined여야 한다고 떴을까요?  (원래 input 태그의 size 속성의 타입을 잘 살펴보시면 유추할 수 있습니다.) 

일단 해당 pr은 머지하도록 하겠습니다. 1주차 과제 수고하셨습니다!

2024-07-02 09:14 UTC, merged