부산대 FE_이지수_1주차 과제 Step2, 3
kakao-tech-campus-2nd-step2/react-gift-react-foundation pull request #68
Opened 2024-06-28 14:35 UTC by dlwltn0430

Step1은 https://github.com/kakao-tech-campus-2nd-step2/react-gift-react-foundation/pull/6 여기서 확인 가능합니다!
브랜치를 새로 만드는 것을 까먹고 step3도 step2 브랜치에 했는데 다음 과제부터는 주의하겠습니다.

2024-06-29 07:59 UTC, MiaJLee requested changes
지수님 안녕하세요~ 첫번째 과제 수행하시느라 고생 많으셨습니다 :) 👏👏👏👏👏

https://github.com/kakao-tech-campus-2nd-step2/react-gift-react-foundation/pull/6 (step 1 PR) 내용 리뷰, 질문에 대한 답변 까지 본 PR에 남겨두겠습니다.

> tsconfig.json 파일에서 alias 설정 후 import "@styles/reset.css라고 적으면 "Module not found: Error: Can't resolve '@styles/reset.css' in 'C:\Users\1\Desktop\react-gift-react-foundation\src'"이라는 에러가 떴었습니다. alias 설정이 제대로 됐는지 확인하기 위해 import Test from "@components/Test"로 테스트를 해보았는데 이 코드는 에러 없이 제대로 동작하고, 왜 @Styles만 에러가 뜨는지 궁금합니다. 또한, 제가 해결한 방법(https://quickest-asterisk-75d.notion.site/TIL-FE-71ea2973e5264154b2eaf50bd268b700 학습일지 Day 3 과제 수행 내용 > 시도한 방법 2)이 올바른 방법인지 궁금합니다.

`react-app-rewired`는 Create React App의 설정을 커스터마이징하려는 개발자들에게 사용되는 도구로 확인됩니다. 보통 웹팩이나 바벨 설정을 편하게 커스터마이징 하기 위해 사용되는 라이브러리라고 합니다. 필요한 경우 서드파티 라이브러리를 설치하여 사용할 수 있지만, 지수님이 원하는 것 처럼 reset.css를 절대 경로로 적용하기 위해 해당 라이브러리를 설치하는 것은 다소 목적에 비해 과한 선택으로 생각되어요. 

해당 라이브러리가 리액트에서 공식적으로 지원되는 방법이 아닌 점, CRA의 내부 구조가 변경되는 경우 예상치 못한 문제가 발생할 수 있다는 점에서 다른 방식을 택하는 것이 더 나을 것으로 판단되어요.


> reset CSS를 적용하기 위해 src/styles 폴더 아래에 reset.css 파일을 생성했는데 index.html의 head 태그 안에 cdn을 import 하는 방식이 더 일반적인가요?

말씀하신대로 head안에 import 하는 방식도 많이 사용이 되고요. 
이외에도 reset.css를 적용하는 다양한 방법이 있습니다.

1. **상대경로로 해당 reset.css를 추가하기** 
2. **CSS 리셋 라이브러리 사용하기**
normalize.css나 sanitize.css와 같은 CSS 리셋 라이브러리를 사용하는 것도 좋은 방법입니다. 이러한 라이브러리는 npm 패키지로 제공되므로, 설치 후에 직접 import하여 사용할 수 있습니다.
```sh
npm install normalize.css
```
```js
import 'normalize.css';
```
3. **CSS in JS 라이브러리 사용하기**
styled-components나 emotion과 같은 CSS in JS 라이브러리에서 제공하는 전역 스타일을 적용하는 기능을 이용할 수 있습니다. 예를 들어, emotion에서는 GlobalStyle을 사용하여 전역 스타일을 정의할 수 있습니다.
```js
import React from 'react';
import { Global, css } from '@emotion/react';

const baseStyle = css`
 // css 설정 내용
 // reset.css 및 원하는 전역 스타일 작성
`;

const GlobalStyle = () => <Global styles={baseStyle} />;

export default GlobalStyle;
```
```js
import Main from 'pages/Main';
import React from 'react';
import GlobalStyle from 'styles/globalStyle';

function App() {
 return (
  <div>
   <GlobalStyle />
   <Main />
  </div>
 );
}

export default App;
```

2024-06-29 07:59 UTC, MiaJLee commented on src/components/Image/Image.tsx
> +}
`getRatio`와 `getRadius` 함수는 실제로는 CSS 속성을 반환하고 있는데요.
이를 더 명확하게 나타내기 위해 함수명을 `getPaddingTop`과 `getBorderRadius`로 변경하는 것을 고려해볼 수 있겠습니다-!

또 예상하지 못한 값이 들어오는 경우 빈 문자열을 반환하고 있는데요. 이 경우 예상치 못한 결과에 대해 알 수 있도록 기본값을 지정해주는 것이 더 좋겠습니다. 예를 들어 아래와 같은 기본값을 줄 수 있어요.

`padding-top: auto;`
`border-radius: 0;`

2024-06-29 07:59 UTC, MiaJLee commented on src/components/Layout/Container.tsx
> +   maxWidth?: string
`maxWidth`에 number 타입도 받아올 수 있도록 수정해본다면 좀 더 가용성 높은 컴포넌트가 될 수 있을 것 같아요.
만일 위와 같이 반영된다면 `CustomContainer` 내부 로직도 조금 변경이 되겠네요!
한번 고민해봐주세요 ㅎㅎ

2024-06-29 07:59 UTC, MiaJLee commented on src/components/Layout/Container.tsx
> +   align-items: ${(props) => props.alignItems || 'flex-star'};
```suggestion
   align-items: ${(props) => props.alignItems || 'flex-start’’;
```
오타가 있네요~!

2024-06-29 07:59 UTC, MiaJLee commented on src/components/GoodsItem/GoodsItem.tsx
> +      </Wrapper>
emotion styled를 활용하여 스타일링을 리액트 컴포넌트 함수 밖에서 지정하신 것 칭찬드려요 👏
마크업 구조를 리턴문에서 한눈에 볼 수 있어 가독성이 높아졌네요 :)

2024-06-29 07:59 UTC, MiaJLee commented on src/components/Image/Image.tsx
> +      return 'border-radius: 50%;'
radius가 circle인 케이스에 border-radius: 100% 이 아닌 50%을 주신 이유가 있을까요? 궁금합니다-!

2024-06-29 07:59 UTC, MiaJLee commented on package.json
> +{
<img width="476" alt="스크린샷 2024-06-29 오후 4 32 47" src="https://github.com/kakao-tech-campus-2nd-step2/react-gift-react-foundation/assets/48678660/9e6eaa4a-912b-4bba-baa6-bf0393fbb18c">

지수님~ 앱 다운로드 후 실행 시 위와 같은 warning 메세지가 확인되는데요-!

앱의 의존성 중 하나인 babel-preset-react-app이 의존성을 선언하지 않은 채로
@babel/plugin-proposal-private-property-in-object 패키지를 가져오고 있어서 발생하는 오류라고 합니다.

해당 에러 수정을 위해 
"@babel/plugin-proposal-private-property-in-object"을 devDependencies에 추가해야합니다.

터미널에서 다음의 명령을 실행하여 devDependency에 추가하면 해결이 됩니다.

```shell
npm install --save-dev @babel/plugin-proposal-private-property-in-object
```

2024-06-29 08:11 UTC, MiaJLee commented on .storybook/main.ts
> +   staticDirs: ['..\\public'],
스토리북 실행 시 해당 staticDirs 설정 때문에 에러가 발생하고 있습니다~
윗줄 제거하니 정상적으로 실행되는 것 확인했습니다. 수정 부탁드릴게요!

2024-07-01 07:20 UTC, dlwltn0430 commented on src/components/Image/Image.tsx
> +      return 'border-radius: 50%;'
모든 모서리에 같은 `border-radius`를 적용할 경우 50%와 100%가 결과에 차이가 없어서 습관적으로 50%라고 적었습니다! 100%로 수정했습니다😊

2024-07-02 01:25 UTC, MiaJLee commented on src/components/Image/Image.tsx
> +      return 'border-radius: 50%;'
@dlwltn0430 
지수님~ 수정한 부분은 pr에 푸시 해주시면 확인할게요~

2024-07-02 23:29 UTC, MiaJLee approved these changes
LGTM 고생하셨습니다-!
지수님 다음 pr부터 change request resolved 처리는 제가 하도록 할게요!

2024-07-02 23:29 UTC, merged

2024-07-03 00:41 UTC, dlwltn0430 commented
> LGTM 고생하셨습니다-! 지수님 다음 pr부터 change request resolved 처리는 제가 하도록 할게요!
상세하게 리뷰해주셔서 정말 많이 도움됐어요! 감사합니다😊